[project]
name = "ticket-classifier-using-langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-ollama>=0.3.3",
    "langgraph>=0.4.8",
    "pymongo[srv]>=4.13.0",
]
